#!/usr/bin/bash
# Corrinne Grover, December 2016

# if less than two arguments supplied, display usage
        if [  $# -le 0 ]
        then
                echo "This script removes sequences from an aligned fasta file that have more than 80% gaps, and then removes remaining alignment positions that have gaps."
                echo "This script requires Python and PyCogent (http://pycogent.org/)"
                # note Pycogent is stupid and cannot take passed variable names as arguments for LoadSeqs. Lame.
                echo -e "\nUsage:\n$0 infile \n"
                exit 1
        fi

# user supplied -h or --help; display usage
        if [[ ( $# == "--help") ||  $# == "-h" ]]
        then
                echo "This script removes sequences from an aligned fasta file that have more than 90% gaps, and then removes remaining alignment positions that have >10% gaps."
                echo "This script requires Python and PyCogent (http://pycogent.org/)"
                echo -e "\nUsage:\n$0 infile \n"
                exit 0
        fi

module load python/2.7.12
module load clustalw/2.1

sed 's/-/_/g' $1 | sed 's/[/]work[/]maa146[/]shane[.]gossypiumD[/][/]analysis[/][/]d[.]align[/]//g' | sed 's/N/-/g' | sed 's/[.]all[.]bam//g' | sed 's/[.][G][a-z][a-z][a-z][a-z][12]//g' | sed 's/4_12/4_12C/' | sed 's/A2_1011/A2_101/' | sed 's/D3_/D3/' > temp.fasta

python - << END

import sys
from cogent import LoadSeqs, DNA

aln = LoadSeqs('temp.fasta', moltype=DNA, format='fasta')
prune_aln = aln.takeSeqs(['A2_44','A2_4', 'A2_BGI'], negate=True)
filtered_aln = prune_aln.omitGapSeqs(0.10)
filtered_gaps = filtered_aln.omitGapPositions(0.1)
filtered_gaps.writeToFile('temp2.fasta')

#sys.exit()
END

sed 's/-/N/g' temp2.fasta > ${1%.fasta}.Nfil.fasta
rm temp.fasta
rm temp2.fasta

outgroups=`grep ">[AF]" ${1%.fasta}.Nfil.fasta | wc -l`

D1=`grep ">D1_" ${1%.fasta}.Nfil.fasta | wc -l`
D2=`grep ">D2_" ${1%.fasta}.Nfil.fasta | wc -l`
D3d=`grep ">D3D" ${1%.fasta}.Nfil.fasta | wc -l`
D3k=`grep ">D3K" ${1%.fasta}.Nfil.fasta | wc -l`
D4=`grep ">D4" ${1%.fasta}.Nfil.fasta | wc -l`
D5=`grep ">D5" ${1%.fasta}.Nfil.fasta | wc -l`
D6=`grep ">D6" ${1%.fasta}.Nfil.fasta | wc -l`
D7=`grep ">D7" ${1%.fasta}.Nfil.fasta | wc -l`
D8=`grep ">D8" ${1%.fasta}.Nfil.fasta | wc -l`
D9=`grep ">D9" ${1%.fasta}.Nfil.fasta | wc -l`
D10=`grep ">D1[10]" ${1%.fasta}.Nfil.fasta | wc -l`


if [ $outgroups  -lt 1 ] || [ $D1 -lt 1 ] || [ $D2 -lt 2 ] ||  [ $D3d -lt 1 ] || [ $D3k -lt 1 ] || [ $D4 -lt 2 ] || [ $D5 -lt 1 ] || [ $D6 -lt 1 ] || [ $D7 -lt 1 ] || [ $D8 -lt 1 ] || [ $D9 -lt 1 ] || [ $D10 -lt 2 ]
then
  mv ${1%.fasta}.Nfil.fasta filtered
else
  clustalw2 -infile=${1%.fasta}.Nfil.fasta -convert -type=nucleotide -output=phylip -outfile=${1%.fasta}.phy
  mv ${1%.fasta}.phy raxml
  clustalw2 -infile=${1%.fasta}.Nfil.fasta -convert -type=nucleotide -output=nexus -outfile=${1%.fasta}.Nfil.nxs 
  echo >> ${1%.fasta}.Nfil.nxs 
  cat ${1%.fasta}.Nfil.nxs bayes.block | sed "s/FILENAME/${1%.fasta}/" > ${1%.fasta}.nxs
  mv ${1%.fasta}.nxs bayes
  rm ${1%.fasta}.Nfil.nxs
  mv ${1%.fasta}.Nfil.fasta fasta
fi


